### ISSUE TITLE
User reload issue

### ISSUE THREAD

**Issue by IvoHristoff** [A62-JS-PG4-WEB/link-up#51]
_when reloading the page, or due to saving the local repo changes, the user is set to be signed out, but it actually isnt. something glitches it out, therefore, after the corrected version of authentication, the user **CAN'T** see any of the nav bars._

**Comment by martinabeleva** [comment]
fixed in:
 e367c85f2c61a92549f7803b74db1e776bbbd020 & 
f81eeb4da99dbe8370eaa736fac46a9c8ee2662e
